name: Deploy Infrastructure

on:
  pull_request:
    branches:
      - master
    paths:
      - terraform/**

jobs:
  tf_fmt:
    permissions: 
      pull-requests: write 
    name: Run terraform plan, comment output on PR
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    
    - name: Generate FAKE SSH keys
      run: echo "some text here" > flipp-key.pub

    - name: Terraform Install
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.6.3"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Create Pull Request Comment with Plan Output
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ### Terraform Plan \`${{ steps.plan.outcome }}\`
          \`\`\`\n
          ${{ steps.plan.outputs.stdout }}
          \`\`\`