name: Deploy Infrastructure

on:
  push:
    branches:
      - master
      paths:
        - terraform/**

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Terraform Install
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.6.3"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Init
      run: terraform init
    
    - name: Generate SSH keys
      run: ssh-keygen -t rsa -b 4096 -f ./flipp-key -q -N ""

    - name: Change permissions for SSH keys
      run: chmod 400 flipp-key
    
    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Create Pull Request
      run: peter-evans/create-pull-request@v5
      title: "Requested changes to infrastructure"
      branch: terraform-changes
      delete-branch: true
      body: |
        ### Terraform Plan \`${{ steps.plan.outcome }}\`
        \`\`\`\n
        ${{ steps.plan.outputs.stdout }}
        \`\`\`
        *Pusher: @${{ github.actor }}