name: Apply Infrastructure Changes

on: workflow_dispatch
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - master
  #   paths:
  #     - terraform/**

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Generate SSH keys
      run: ssh-keygen -t rsa -b 4096 -f ./flipp-key -q -N ""

    - name: Change permissions for SSH keys
      run: chmod 400 flipp-key

    - name: Terraform Install
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.6.3"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Configure Infrastructure
      run: |
        ssh -i flipp-key -o StrictHostKeychecking=no ec2-user@$(terraform output -raw public_ip) "sudo yum install git -y;sudo yum install nginx -y;git clone https://github.com/jameswei1/flipp-takehome.git"
        ssh -i flipp-key -o StrictHostKeychecking=no ec2-user@$(terraform output -raw public_ip) "sudo mv flipp-takehome/nginx.conf /etc/nginx/nginx.conf -f;sudo systemctl start nginx"
        ssh -i flipp-key -o StrictHostKeychecking=no ec2-user@$(terraform output -raw public_ip) "sudo yum install nodejs -y;sudo npm install forever -g;cd flipp-takehome;npm install;forever start server.js"
